---
- name: configuring MPBGP and vrf-interfaces of PE1
  hosts: PE1router
  gather_facts: false
  tasks:
    - name: configure PE1 interface GigabitEthernet0/0
      ios_config:
        lines:
          - description Configured by ANSIBLE!!!
          - ip add 10.0.1.1 255.255.255.252
          - no sh
        parents: interface GigabitEthernet0/0
    - name: configure PE1 interface GigabitEthernet0/2
      ios_config:
        lines:
          - description Configured by ANSIBLE!!!
          - ip add 10.0.1.5 255.255.255.252
          - no sh
        parents: interface GigabitEthernet0/2
    - name: Configure MPBGP at PE1
      ios_config:
        lines:
          - neighbor 10.0.0.4 remote-as 65000
          - neighbor 10.0.0.4 update-source Loopback0
          - address-family vpnv4
          - neighbor 10.0.0.4 activate
          - neighbor 10.0.0.4 send-community extended
        parents:  router bgp 65000

#PE-2 interfaces configs
- name: configuring MPBGP and vrf-interfaces of PE2
  hosts: PE2router
  gather_facts: false
  tasks:
    - name: configure PE2 interface GigabitEthernet0/0
      ios_config:
        lines:
          - description Configured by ANSIBLE!!!
          - ip add 10.0.2.1 255.255.255.252
          - no sh
        parents: interface GigabitEthernet0/0
    - name: configure PE2 interface GigabitEthernet0/2
      ios_config:
        lines:
          - description Configured by ANSIBLE!!!
          - ip add 10.0.2.5 255.255.255.252
          - no sh
        parents: interface GigabitEthernet0/2
    - name: Configure MPBGP at PE2
      ios_config:
        lines:
          - neighbor 10.0.0.3 remote-as 65000
          - neighbor 10.0.0.3 update-source Loopback0
          - address-family vpnv4
          - neighbor 10.0.0.3 activate
          - neighbor 10.0.0.3 send-community extended
        parents:  router bgp 65000
